[package]
name = "restore_watermark"
version = "0.1.0"
edition = "2021"

[dependencies]
ttf-parser = "0.20"
unicode-segmentation = "1.11"
rayon = "1.8"
regex = "1.10"
rand = "0.8"
rand_chacha = "0.3"
rustfft = "6.1"
